ALTER TABLE ALIAS
ADD FOREIGN KEY (personKey) REFERENCES PERSON(personKey);

ALTER TABLE PUBLICATION
ADD FOREIGN KEY (publisherId) REFERENCES PUBLISHER(publisherId);


ALTER TABLE PUBMONTH
ADD FOREIGN KEY (pubKey) REFERENCES PUBLICATION(pubKey);

ALTER TABLE ARTICLE
ADD FOREIGN KEY (pubKey) REFERENCES PUBLICATION(pubKey),
ADD FOREIGN KEY (articleCrossRef) REFERENCES PUBLICATION(pubKey);

ALTER TABLE PROCEEDING
ADD FOREIGN KEY (pubKey) REFERENCES PUBLICATION(pubKey);

ALTER TABLE INPROCEEDING
ADD FOREIGN KEY (pubKey) REFERENCES PUBLICATION(pubKey),
ADD FOREIGN KEY (inproCrossRef) REFERENCES PUBLICATION(pubKey);

ALTER TABLE BOOK
ADD FOREIGN KEY (pubKey) REFERENCES PUBLICATION(pubKey);

ALTER TABLE INCOLLECTION
ADD FOREIGN KEY (pubKey) REFERENCES PUBLICATION(pubKey),
ADD FOREIGN KEY (incolCrossRef) REFERENCES PUBLICATION(pubKey);

ALTER TABLE THESIS
ADD FOREIGN KEY (pubKey) REFERENCES PUBLICATION(pubKey);

ALTER TABLE WWW
ADD FOREIGN KEY (pubKey) REFERENCES PUBLICATION(pubKey);


/* ========================================================================= */
/* Associative Tables                                                        */
/* ========================================================================= */

ALTER TABLE AUTHORSHIP
ADD FOREIGN KEY (pubKey) REFERENCES PUBLICATION(pubKey),
ADD FOREIGN KEY (personKey) REFERENCES PERSON(personKey);

ALTER TABLE EDITORSHIP
ADD FOREIGN KEY (pubKey) REFERENCES PUBLICATION(pubKey),
ADD FOREIGN KEY (personKey) REFERENCES PERSON(personKey);

ALTER TABLE CITERSHIP
ADD FOREIGN KEY (citingPubKey) REFERENCES PUBLICATION(pubKey),
ADD FOREIGN KEY (citedPubKey) REFERENCES PUBLICATION(pubKey);

ALTER TABLE PUB_SCHOOL
ADD FOREIGN KEY (schoolId) REFERENCES SCHOOL(schoolId),
ADD FOREIGN KEY (pubKey) REFERENCES PUBLICATION(pubKey);
