/* ========================================================================= */
/* Set Constraints                                                           */
/* ========================================================================= */

ALTER TABLE ALIAS
ADD FOREIGN KEY (personKey) REFERENCES PERSON(personKey),
MODIFY COLUMN aliasFirstName VARCHAR(100) NOT NULL;

ALTER TABLE PUBLICATION
ADD PRIMARY KEY(pubKey),
ADD FOREIGN KEY (publisherId) REFERENCES PUBLISHER(publisherId);

ALTER TABLE PUBMONTH
ADD FOREIGN KEY (pubKey) REFERENCES PUBLICATION(pubKey);

ALTER TABLE ARTICLE
ADD FOREIGN KEY (pubKey) REFERENCES PUBLICATION(pubKey);

ALTER TABLE PROCEEDING
ADD FOREIGN KEY (pubKey) REFERENCES PUBLICATION(pubKey);

ALTER TABLE INPROCEEDING
ADD FOREIGN KEY (pubKey) REFERENCES PUBLICATION(pubKey);

ALTER TABLE BOOK
ADD FOREIGN KEY (pubKey) REFERENCES PUBLICATION(pubKey);

ALTER TABLE INCOLLECTION
ADD FOREIGN KEY (pubKey) REFERENCES PUBLICATION(pubKey);

ALTER TABLE THESIS
ADD FOREIGN KEY (pubKey) REFERENCES PUBLICATION(pubKey);

ALTER TABLE WWW
ADD FOREIGN KEY (pubKey) REFERENCES PUBLICATION(pubKey);

ALTER TABLE EDITORSHIP
ADD FOREIGN KEY (pubKey) REFERENCES PUBLICATION(pubKey),
ADD FOREIGN KEY (personKey) REFERENCES PERSON(personKey);

ALTER TABLE PUB_SCHOOL
ADD PRIMARY KEY(schoolId, pubKey),
ADD FOREIGN KEY (schoolId) REFERENCES SCHOOL(schoolId),
ADD FOREIGN KEY (pubKey) REFERENCES PUBLICATION(pubKey);



ALTER TABLE CITERSHIP
ADD FOREIGN KEY (citingPubKey) REFERENCES PUBLICATION(pubKey),
ADD FOREIGN KEY (citedPubKey) REFERENCES PUBLICATION(pubKey);

ALTER TABLE AUTHORSHIP
ADD PRIMARY KEY(pubKey, personKey),
ADD FOREIGN KEY (pubKey) REFERENCES PUBLICATION(pubKey),
ADD FOREIGN KEY (personKey) REFERENCES PERSON(personKey);


SHOW ENGINE INNODB STATUS;

ALTER TABLE ARTICLE
ADD FOREIGN KEY (articleCrossref) REFERENCES PUBLICATION(pubKey);

ALTER TABLE INPROCEEDING
ADD FOREIGN KEY (inproCrossref) REFERENCES PUBLICATION(pubKey);

ALTER TABLE INCOLLECTION
ADD FOREIGN KEY (incolCrossref) REFERENCES PUBLICATION(pubKey);

SELECT COUNT(*) FROM ALIAS;
SELECT COUNT(*) FROM PERSON;
SELECT COUNT(*) FROM PUBLICATION;
SELECT COUNT(*) FROM PUBLISHER;
